[package]
name = "mini_runtime"
version = "0.1.0"
edition = "2024"
authors = ["Leo Cheng <chengkelfan@foxmail.com>"]
description = "Mini async runtime for rust"
license = "MIT"

[dependencies]
rand = "0.9"
