[package]
name = "mini_runtime_derive"
version = "0.1.0"
edition = "2024"
authors = ["Leo Cheng <chengkelfan@foxmail.com>"]
description = "Macro for mini async runtime"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
